# Generated by Django 4.1.4 on 2023-01-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
