# Generated by Django 4.1.4 on 2023-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watched_by', to='auctions.listing'),
        ),
    ]
